# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy CI

on:
  push:
    branches: [ "debug" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check DNS Resolution
      run: nslookup ${{ secrets.VPS_IP }}

    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./
        remote: ~/target/directory
        host: ${{ secrets.VPS_IP }}
        port: 59666
        username: ${{ secrets.VPS_USER }}
        privateKey: ${{ secrets.VPS_SSH_KEY }}