# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy_vps:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Execute deploy script
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} '
          cd /root/projects/sdufReactNative &&
          echo "in folder" &&
          git restore . &&
          echo "git restore" &&
          git pull &&
          echo "git pull"
          exit 0
        '